package com.unitechApi.user.model;

public enum ERole {
    ROLE_ADMIN,
    ROLE_SUBADMIN,
    ROLE_GENERALMANAGER,
    ROLE_PURCHASER,
    ROLE_ACCOUNT,
    ROLE_SUPERVISOR,
    ROLE_QC,
    ROLE_SECURITY,
    ROLE_HR,
    ROLE_CASTER,
    ROLE_LEBOR,
    ROLE_MAINTENANCE,
    ROLE_STORE
}

